### ISSUE TITLE
FileNotFoundError during google colab training

### ISSUE THREAD

**Issue by InukKang** [hasanirtiza/Pedestron#113]
**Checklist**
1. I have searched related issues but cannot get the expected help.

**Describe the bug**
FileNotFoundError for datasets. I uploaded datasets but don't know what is reason

**Reproduction**
1. What command or script did you run?
!cd /content/Pedestron/
!python /content/Pedestron/tools/train.py /content/Pedestron/configs/elephant/cityperson/cascade_hrnet.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No

3. What dataset did you use?
Cityperson

**Environment**
Google Colab

**Error traceback**
2021-09-29 17:07:18,195 - INFO - Distributed training: False
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
2021-09-29 17:07:21,540 - INFO - Start running, host: root@045b7727b0d3, work_dir: /content/work_dirs/cityperson_cascade_rcnn_hrnetv2p_w32
2021-09-29 17:07:21,541 - INFO - workflow: [('train', 1)], max: 240 epochs
Traceback (most recent call last):
  File "/content/Pedestron/tools/train.py", line 98, in <module>
    main()
  File "/content/Pedestron/tools/train.py", line 94, in main
    logger=logger)
  File "/content/Pedestron/mmdet/apis/train.py", line 63, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/content/Pedestron/mmdet/apis/train.py", line 219, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/Pedestron/mmdet/datasets/custom.py", line 189, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/Pedestron/mmdet/datasets/custom.py", line 198, in prepare_train_img
    img = mmcv.imread(osp.join(self.img_prefix, img_info['filename']))
  File "/usr/local/lib/python3.7/site-packages/mmcv/image/io.py", line 41, in imread
    'img file does not exist: {}'.format(img_or_path))
  File "/usr/local/lib/python3.7/site-packages/mmcv/utils/path.py", line 32, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: [/content/Pedestron/datasets/CityPersons/leftImg8bit_trainvaltest//leftImg8bit/train/strasbourg/strasbourg_000001_041215_leftImg8bit.png

<img width="237" alt="화1" src="https://user-images.githubusercontent.com/69806620/135317188-4c0ac87b-4280-42b4-9251-b68c6d73461d.PNG">
<img width="656" alt="화2" src="https://user-images.githubusercontent.com/69806620/135317191-bf73aff1-8f2c-4ebe-ae30-52b14ee0b40e.PNG">
<img width="407" alt="화3" src="https://user-images.githubusercontent.com/69806620/135317192-60541e9c-b214-40ac-ab52-c95dbe8aa3e7.PNG">

**Comment by hasanirtiza** [comment]
I mean it is 100% a path issue, if I were you, this what I would do, open terminal, navigate to the folder `train` and hit `pwd` (assuming linux or mac etc.),  simply compare your paths. Somehow my impression is, you `work_dir` is in `content` folder and your code appears to be in `content/Pedestron` ... Not sure if that is messing up.
