### ISSUE TITLE
AssertionError: MMCV==0.2.14 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0.

### ISSUE THREAD

**Issue by AndyVerne** [hasanirtiza/Pedestron#117]
First, thanks for the great work. 
Since I follow the [install instruction](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) to install the mmcv version==0.2.14, it's fine to run the demo.py , but when I test the Euro CityPersons dataset,  the assertion error occurred.

This is the test command:
```
python ./tools/test_euroCity.py configs/elephant/eurocity/cascade_hrnet.py ./models_pretrained/epoch_ 147 148 --mean_teacher
```
This is the AssertionError
```
Traceback (most recent call last):
  File "./tools/test_euroCity.py", line 12, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result
  File "/root/mmdetection/mmdet/__init__.py", line 26, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==0.2.14 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0.
```

**Comment by AndyVerne** [comment]
Sorry to bother you. 
I've fixed it. 
Here is my solution: Just pip uninstall the mmdet which included in mmdetection. And instead of it, install the mmdet which included in Pedestron.
