### ISSUE TITLE
Cannot execute succesfully the run.py

### ISSUE THREAD

**Issue by nodiz** [hasanirtiza/Pedestron#12]
Hello, 

first of all, thank you for the work done to provide such an amazing collection of code.

Following the installation tutorial, we run into a runtime error when CUDA optimized files are being compiled from the setup.py file.

We are using the google cloud deep learning VM, here are the dependencies we have in our machine

. Debian GNU/Linux 9.11 (stretch)
. Gcc 6.3.0 
. Cuda 10.1
. NCCL 2.4.8
. Python 3.7.7
. Torch 1.5 stable cuda 10.1
. Using conda

**Error traceback**

```
In file included from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/nodiz/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:1:
/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "setup.py", line 199, in <module>
    zip_safe=False)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/nodiz/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

**Bug fix**

Not yet. 

Any suggestion?

**Comment by hasanirtiza** [comment]
Couple of recommendations:
1)  PyTorch version, currently Pedestron does not support 1.5. We have tested Pedestron with 1.4.0. Also [here](https://github.com/open-mmlab/mmdetection/issues/2517).
2) Optionally, I would recommend you to try Cuda 10.0 first, if you can, after solving the PyTorch version.
