### ISSUE TITLE
ImportError: /pedestron/tools/../mmdet/ops/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by fuma8** [hasanirtiza/Pedestron#156]
**Reproduction**
Hello, 
I made the environment by Docker like [this page](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md).

1. What command or script did you run?
```
python tools/demo.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_5.pth.stu demo/ result_demo/
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
 - OS: Ubuntu20.04
 - GCC 5.4.0
 - PyTorch version 1.10.2+cu102
- How you installed PyTorch pip
- GPU model 
- CUDA and CUDNN version 10.1

**Error traceback**
If applicable, paste the error trackback here.
```
root@7c08cb4155c7:/pedestron# python tools/demo.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_5.pth.stu demo/ result_demo/ 
Traceback (most recent call last):
  File "tools/demo.py", line 14, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result
  File "/pedestron/tools/../mmdet/apis/__init__.py", line 2, in <module>
    from .train import train_detector
  File "/pedestron/tools/../mmdet/apis/train.py", line 7, in <module>
    from mmdet.core.my_mmcv.runner.mean_teacher_runner import Mean_teacher_Runner as Runner
  File "/pedestron/tools/../mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/pedestron/tools/../mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/pedestron/tools/../mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/pedestron/tools/../mmdet/ops/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/pedestron/tools/../mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File "/pedestron/tools/../mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from .. import deform_conv_cuda
ImportError: /pedestron/tools/../mmdet/ops/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
```

**Comment by hasanirtiza** [comment]
I think the problem is related to your PyTorch and mmdetection versions. A similar issue was opened [here](https://github.com/open-mmlab/mmdetection/issues/1554).  Check [installation.md](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md) file for version references.
