### ISSUE TITLE
RuntimeError: One of the variables has been modified by an inplace operation

### ISSUE THREAD

**Issue by dtch1997** [hasanirtiza/Pedestron#58]
**Describe the bug**
Training Cascade HRNet on CrowdHuman fails. 

**Reproduction**
First, I applied this fix https://github.com/hasanirtiza/Pedestron/issues/17 for a different error. 
```
python tools/train.py configs/elephant/crowdhuman/cascade_hrnet.py 
```
No modifications were made to the base config. Dataset used is CrowdHuman. 

**Environment**
 - OS: [e.g., Ubuntu 18.04]
 - GCC 6.3.0
 - PyTorch version 1.2.0
- How you installed PyTorch: conda
- GPU model: Tesla K80
- CUDA and CUDNN version: 10.0

**Error traceback**
```
Traceback (most recent call last):
  File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 94, in main
    logger=logger)
  File "/home/dtch009/Pedestron/mmdet/apis/train.py", line 63, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/dtch009/Pedestron/mmdet/apis/train.py", line 228, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_iter')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/dtch009/Pedestron/mmdet/core/my_mmcv/runner/hooks/mean_teacher_optimizer.py", line 18, in after_train_iter
    runner.outputs['loss'].backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 256, 14, 14]], which is output 0 of IndexPutBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Bug fix**
Based on [this issue](https://github.com/NVlabs/FUNIT/issues/23), it seems like the reason for the bug is the use of torch.nn.Relu with "inplace=True". I fixed this in `mmdet/models/necks/hrfpn.py` as follows: 
```
        self.fpn_convs = nn.ModuleList()
        for i in range(self.num_outs):
            self.fpn_convs.append(
                ConvModule(
                    out_channels,
                    out_channels,
                    kernel_size=3,
                    padding=1,
                    conv_cfg=self.conv_cfg,
                    activation=None,
                    inplace=False))
```
I am still trying to find the other instances of nn.Relu

**Comment by hasanirtiza** [comment]
I cannot reproduce this issue locally. Can you also just print the versions of you mmdet ?

**Comment by dtch1997** [comment]
> 
> 
> I cannot reproduce this issue locally. Can you also just print the versions of you mmdet ?

It's the same as what is downloaded in the Colab tutorial. MMCV 0.2.14. Let me check my version of MMDet.
