### ISSUE TITLE
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'  ，when I train ,it cause this problem? How can I do in colab?

### ISSUE THREAD

**Issue by zhangyu13141** [hasanirtiza/Pedestron#60]

**Comment by zhangyu13141** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 94, in main
    logger=logger)
  File "/content/drive/My Drive/Pedestron/mmdet/apis/train.py", line 63, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/content/drive/My Drive/Pedestron/mmdet/apis/train.py", line 228, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/content/drive/My Drive/Pedestron/mmdet/apis/train.py", line 41, in batch_processor
    losses = model(**data)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Pedestron/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/content/drive/My Drive/Pedestron/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/content/drive/My Drive/Pedestron/mmdet/models/detectors/cascade_rcnn.py", line 137, in forward_train
    *rpn_loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/content/drive/My Drive/Pedestron/mmdet/models/anchor_heads/rpn_head.py", line 51, in loss
    gt_bboxes_ignore=gt_bboxes_ignore)
  File "/content/drive/My Drive/Pedestron/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/content/drive/My Drive/Pedestron/mmdet/models/anchor_heads/anchor_head.py", line 179, in loss
    sampling=self.sampling)
  File "/content/drive/My Drive/Pedestron/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/content/drive/My Drive/Pedestron/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/content/drive/My Drive/Pedestron/mmdet/core/anchor/anchor_target.py", line 105, in anchor_target_single
    inside_flags = anchor_inside_flags(flat_anchors, valid_flags,img_meta['img_shape'][:2],cfg.allowed_border)
  File "/content/drive/My Drive/Pedestron/mmdet/core/anchor/anchor_target.py", line 173, in anchor_inside_flags
    (flat_anchors[:, 2] < img_w + allowed_border) & \
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'

**Comment by hasanirtiza** [comment]
#17

**Comment by SoumiDas** [comment]
Changing line number 173 in mmdet/core/anchor/anchor_target.py

from

```
inside_flags = valid_flags &
(flat_anchors[:, 0] >= -allowed_border) &
(flat_anchors[:, 1] >= -allowed_border) &
(flat_anchors[:, 2] < img_w + allowed_border) &
(flat_anchors[:, 3] < img_h + allowed_border)
```

to

```
inside_flags = valid_flags.bool() &
(flat_anchors[:, 0] >= -allowed_border) &
(flat_anchors[:, 1] >= -allowed_border) &
(flat_anchors[:, 2] < img_w + allowed_border) &
(flat_anchors[:, 3] < img_h + allowed_border)
```

also solves the above issue.
