### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by anshulpaigwar** [hasanirtiza/Pedestron#74]
Error with compiling roi_align extension during the installation process. The error seems to be related to the pytorch version. The ATen library may be not compatible. I could not understand how to resolve this issue. I would appreciate it if some could help me.

**Reproduction**
```
python setup.py develop
```

**Environment**
 - OS: Ubuntu 18.04
 - GCC 7.5
 - PyTorch version 1.5.1
-  PyTorch installed using pip
- GPU model GTX1080
- CUDA  version 10.2

**Error traceback**
```
In file included from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:1:
/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:20:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:20:23: note: in definition of macro ‘CHECK_CUDA’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^~~~~~~~
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:31:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(features);
   ^
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:20:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:20:23: note: in definition of macro ‘CHECK_CUDA’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^~~~~~~~
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:31:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(features);
   ^
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:20:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                       ^
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:24:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(x);       \
   ^~~~~~~~~~
/home/anshul/es3cap/my_codes/Pedestron/mmdet/ops/roi_align/src/roi_align_cuda.cpp:32:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(rois);
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 199, in <module>
    zip_safe=False)
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 437, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/anshul/es3cap/env/py3_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

**Comment by hasanirtiza** [comment]
Revert your PyTorch version to 1.1.0 (we have tested it with <=1.4.0) and should be good to go. Have a look [here](https://github.com/open-mmlab/mmdetection/issues/3513).

**Comment by anshulpaigwar** [comment]
The main issue causing this error is AT_CHECK
```
error: ‘AT_CHECK’ was not declared in this scope
``` 

The new pytorch 1.5 has replaced AT_CHECK with AT_ASSERT

I solved this issue by replacing AT_CHECK with AT_ASSERT in all the code for all the extensions. Also `x.type().is_cuda()`  is deprecated we can simply use `x.is_cuda() `

Replacing line 20 in roi_align_cuda.cpp with the following solves the error and warnings.
```
#define CHECK_CUDA(x) AT_ASSERT(x.is_cuda(), #x, " must be a CUDAtensor ")
```
