### ISSUE TITLE
trying to get Pedestron work on Ubuntu 20.04

### ISSUE THREAD

**Issue by akosmaroy** [hasanirtiza/Pedestron#88]
Hi,

I'm new to Pedestron, and I'm trying to make it work on an Ubuntu 20.04 box. 

I've documented the actual steps taking for installation in this doc: https://docs.google.com/document/d/1cmFuGJvb1PQzJwAj7WDBUy-CEepIqpUE7WCY2dXbfKQ/edit?usp=sharing

I've managed to get MMDetection work, prior to attemtping to get Pedestron work.

My envorionent:
 - OS: Ubuntu 20.04
 - GCC: 9.3.0
 - PyTorch version: 1.4.0
 - How I installed PyTorch: pip install torch==1.4.0 torchvision==0.5.0
 - GPU model: GTX 1070
 - CUDA and CUDNN: 10.1

more environment information in the google doc linked above

After going through the Pedestron install process, I'm trying to execute the following

```
$ python tools/demo.py configs/elephant/cityperson/cascade_hrnet.py ./models_pretrained/epoch_147.pth.stu demo/ result_demo/
Traceback (most recent call last):
  File "tools/demo.py", line 14, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/apis/__init__.py", line 2, in <module>
    from .train import train_detector
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/apis/train.py", line 7, in <module>
    from mmdet.core.my_mmcv.runner.mean_teacher_runner import Mean_teacher_Runner as Runner
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/core/evaluation/__init__.py", line 5, in <module>
    from .eval_hooks import (DistEvalHook, DistEvalmAPHook, CocoDistEvalRecallHook,
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/core/evaluation/eval_hooks.py", line 16, in <module>
    from mmdet import datasets
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/datasets/__init__.py", line 6, in <module>
    from .loader import GroupSampler, DistributedGroupSampler, build_dataloader
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/datasets/loader/__init__.py", line 1, in <module>
    from .build_loader import build_dataloader
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/datasets/loader/build_loader.py", line 8, in <module>
    from .sampler import GroupSampler, DistributedGroupSampler, DistributedSampler
  File "/home/akos/src/people_track/src/Pedestron/tools/../mmdet/datasets/loader/sampler.py", line 7, in <module>
    from mmcv.runner.utils import get_dist_info
ImportError: cannot import name 'get_dist_info' from 'mmcv.runner.utils' (/home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/utils.py)
```

This is even though mmcv seems to be there fine:

```
$ python -c 'import mmcv; import mmcv.ops'
# reports no errors
```

This is the output of my Pedestron install script:

```
$ pip install -v -e .
Using pip 21.0.1 from /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-t77fo1n6
Created temporary directory: /tmp/pip-req-tracker-3a2zphje
Initialized build tracking at /tmp/pip-req-tracker-3a2zphje
Created build tracker: /tmp/pip-req-tracker-3a2zphje
Entered build tracker: /tmp/pip-req-tracker-3a2zphje
Created temporary directory: /tmp/pip-install-wdp3w_zo
Obtaining file:///home/akos/src/people_track/src/Pedestron
  Added file:///home/akos/src/people_track/src/Pedestron to build tracker '/tmp/pip-req-tracker-3a2zphje'
    Running setup.py (path:/home/akos/src/people_track/src/Pedestron/setup.py) egg_info for package from file:///home/akos/src/people_track/src/Pedestron
    Created temporary directory: /tmp/pip-pip-egg-info-9afcrp81
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-9afcrp81/mmdet.egg-info
    writing /tmp/pip-pip-egg-info-9afcrp81/mmdet.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-9afcrp81/mmdet.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-9afcrp81/mmdet.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-9afcrp81/mmdet.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-9afcrp81/mmdet.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-9afcrp81/mmdet.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-9afcrp81/mmdet.egg-info/SOURCES.txt'
  Source in /home/akos/src/people_track/src/Pedestron has version 0.6.0+c7e286f, which satisfies requirement mmdet==0.6.0+c7e286f from file:///home/akos/src/people_track/src/Pedestron
  Removed mmdet==0.6.0+c7e286f from file:///home/akos/src/people_track/src/Pedestron from build tracker '/tmp/pip-req-tracker-3a2zphje'
Requirement already satisfied: mmcv>=0.2.6 in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmdet==0.6.0+c7e286f) (1.2.7)
Requirement already satisfied: numpy in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmdet==0.6.0+c7e286f) (1.20.1)
Requirement already satisfied: matplotlib in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmdet==0.6.0+c7e286f) (3.3.4)
Requirement already satisfied: six in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmdet==0.6.0+c7e286f) (1.15.0)
Requirement already satisfied: terminaltables in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmdet==0.6.0+c7e286f) (3.1.0)
Requirement already satisfied: pycocotools in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmdet==0.6.0+c7e286f) (2.0.2)
Requirement already satisfied: torch>=1.1 in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmdet==0.6.0+c7e286f) (1.4.0)
Requirement already satisfied: pyyaml in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmcv>=0.2.6->mmdet==0.6.0+c7e286f) (5.4.1)
Requirement already satisfied: Pillow in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmcv>=0.2.6->mmdet==0.6.0+c7e286f) (8.1.2)
Requirement already satisfied: yapf in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmcv>=0.2.6->mmdet==0.6.0+c7e286f) (0.30.0)
Requirement already satisfied: addict in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from mmcv>=0.2.6->mmdet==0.6.0+c7e286f) (2.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from matplotlib->mmdet==0.6.0+c7e286f) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from matplotlib->mmdet==0.6.0+c7e286f) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from matplotlib->mmdet==0.6.0+c7e286f) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from matplotlib->mmdet==0.6.0+c7e286f) (2.4.7)
Requirement already satisfied: cython>=0.27.3 in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from pycocotools->mmdet==0.6.0+c7e286f) (0.29.22)
Requirement already satisfied: setuptools>=18.0 in /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages (from pycocotools->mmdet==0.6.0+c7e286f) (52.0.0.post20210125)
Created temporary directory: /tmp/pip-unpack-hal9l3_3
Installing collected packages: mmdet
  Attempting uninstall: mmdet
    Found existing installation: mmdet 0.6.0+c7e286f
    Uninstalling mmdet-0.6.0+c7e286f:
      Created temporary directory: /tmp/pip-uninstall-x98pcu4x
      Removing file or directory /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet.egg-link
      Removing pth entries from /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/easy-install.pth:
      Removing entry: /home/akos/src/people_track/src/Pedestron
      Successfully uninstalled mmdet-0.6.0+c7e286f
  Running setup.py develop for mmdet
    Running command /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/akos/src/people_track/src/Pedestron/setup.py'"'"'; __file__='"'"'/home/akos/src/people_track/src/Pedestron/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    copying build/lib.linux-x86_64-3.8/mmdet/ops/nms/soft_nms_cpu.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/nms
    copying build/lib.linux-x86_64-3.8/mmdet/ops/roi_align/roi_align_cuda.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/roi_align
    copying build/lib.linux-x86_64-3.8/mmdet/ops/roi_pool/roi_pool_cuda.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/roi_pool
    copying build/lib.linux-x86_64-3.8/mmdet/ops/nms/nms_cpu.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/nms
    copying build/lib.linux-x86_64-3.8/mmdet/ops/nms/nms_cuda.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/nms
    copying build/lib.linux-x86_64-3.8/mmdet/ops/dcn/deform_conv_cuda.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/dcn
    copying build/lib.linux-x86_64-3.8/mmdet/ops/dcn/deform_pool_cuda.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/dcn
    copying build/lib.linux-x86_64-3.8/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss_cuda.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/sigmoid_focal_loss
    copying build/lib.linux-x86_64-3.8/mmdet/ops/masked_conv/masked_conv2d_cuda.cpython-38-x86_64-linux-gnu.so -> mmdet/ops/masked_conv
    Creating /home/akos/src/people_track/usr/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet.egg-link (link to .)
    Adding mmdet 0.6.0+c7e286f to easy-install.pth file

    Installed /home/akos/src/people_track/src/Pedestron
Successfully installed mmdet
Removed build tracker: '/tmp/pip-req-tracker-3a2zphje'
```

I wonder what I'm missing of what I'm doing wrong.

**Comment by hasanirtiza** [comment]
From the log, most likely problem is with mmcv (its version). In the doc file you provided, you are using 1.2.4, it is too higher of a version. Simply downgrading mmcv should work. We have enlisted details (also versions) in the [installation file](https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md). Check the version of mmcv first, `print(mmcv.__version__)`, (We have tested Pedestron using mmcv==0.2.10 and 0.2.14). Similar issue was discussed here previously as well #11. Your PyTorch version seems fine to me. By the way, incase you have not seen already, may be this step by step installation in [google colab demo](https://github.com/hasanirtiza/Pedestron/blob/master/colab/PedestronColab.ipynb) can also help.

**Comment by akosmaroy** [comment]
Thank you. Indeed:

```
pip install mmcv==0.2.14
pip install -v -e .
```

Made the demo script work. Thank you!

I also tried t0 install mmcv 0.2.10 or 0.2.14 CUDA versions, but these didn't work:

```
$ export torch_version=torch1.4.0
$ export cu_version=cu101
$ export mmcv_version=0.2.10
$ pip install mmcv-full==${mmcv_version} -f https://download.openmmlab.com/mmcv/dist/${cu_version}/${torch_version}/index.html
Looking in links: https://download.openmmlab.com/mmcv/dist/cu101/torch1.4.0/index.html
ERROR: Could not find a version that satisfies the requirement mmcv-full==0.2.10
ERROR: No matching distribution found for mmcv-full==0.2.10
$ export mmcv_version=0.2.14
$ pip install mmcv-full==${mmcv_version} -f https://download.openmmlab.com/mmcv/dist/${cu_version}/${torch_version}/index.html
Looking in links: https://download.openmmlab.com/mmcv/dist/cu101/torch1.4.0/index.html
ERROR: Could not find a version that satisfies the requirement mmcv-full==0.2.14
ERROR: No matching distribution found for mmcv-full==0.2.14
```

**Comment by hasanirtiza** [comment]
Previously, it was called only `mmcv` and this is what Pedestron expects. Later on, the `mmedetection` guys renamed it to `mmcv-full`. Hopefully this will solve, as you are installing `mmcv-full`, instead you need only `pip install mmcv==${mmcv_version}`. One more caveat,  as per my personal experience, if you are working with `conda` environments and also use `mmdetection` for any other project, make sure that you have separate environments for `Pedestron` and `mmdetection`.

**Comment by akosmaroy** [comment]
thank you - updated the google doc linked above

**Comment by hasanirtiza** [comment]
I think we will add the google doc link to readme. People might find it useful for installation. Thanks.
